pre_process :
  dask_cluster :
    available: False
    n_workers : 2
    memory_limit : 2GiB
  download_api : kaggle datasets download -d thoughtvector/customer-support-on-twitter
  zip_filename : customer-support-on-twitter.zip
  dir : ./data
  file_data_path: ./data/twcs/twcs.csv
  text_column : text
  processed_file_name : processed

data_encoding:
  dask_cluster :
    available: False
    n_workers : 2
    memory_limit : 2GiB
  processed_file_path : ./data/processed/
  start_df : 1
  end_df : 400
 
defaults:  
  - override hydra/job_logging: None
  - override hydra/hydra_logging: None


  - _self_

hydra:
  output_subdir: null
  run:
    dir: .

