pre_process :
  dask_cluster :
    available: False
    n_workers : 2
    memory : 1GiB
  download_api : kaggle datasets download -d thoughtvector/customer-support-on-twitter
  zip_filename : customer-support-on-twitter.zip
  dir : ./data
  file_data_path: ./data/twcs/twcs.csv
  text_column : text
  processed_file_name : processed.csv


defaults:  
  - override hydra/job_logging: None
  - override hydra/hydra_logging: None


  - _self_

hydra:
  output_subdir: null
  run:
    dir: .

