pre_process :
  download_api : kaggle datasets download -d thoughtvector/customer-support-on-twitter
  zip_filename : customer-support-on-twitter.zip
  dir : ./data
  file_data_path: ./data/twcs/twcs.csv
  text_column : text


defaults:  
  - override hydra/job_logging: None
  - override hydra/hydra_logging: None


  - _self_

hydra:
  output_subdir: null
  run:
    dir: .

